In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("books_with_emotion.csv")

In [3]:
dataset.head()

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,title_and_subtitle,tagged_description,simple_categories,anger,disgust,fear,joy,sadness,surprise,neutral
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,...,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction,0.064134,0.273591,0.928168,0.932798,0.646216,0.967158,0.729602
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction,0.612619,0.348284,0.942528,0.704422,0.887940,0.111690,0.252546
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,...,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction,0.064134,0.104007,0.972321,0.767239,0.549477,0.111690,0.078765
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,...,The Four Loves,9780006280897 Lewis' work on the nature of lov...,Nonfiction,0.351485,0.150722,0.360705,0.251882,0.732685,0.111690,0.078765
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,...,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",Nonfiction,0.081412,0.184496,0.095043,0.040564,0.884390,0.475880,0.078765

In [4]:
dataset.sample()

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,title_and_subtitle,tagged_description,simple_categories,anger,disgust,fear,joy,sadness,surprise,neutral
3376,9780743284882,0743284887,Chuck Klosterman IV,Chuck Klosterman,Biography & Autobiography,http://books.google.com/books/content?id=z8Zb3...,A collection by the pop culture commentator in...,2006.0,3.85,374.0,...,Chuck Klosterman IV: A Decade of Curious Peopl...,9780743284882 A collection by the pop culture ...,Nonfiction,0.023972,0.028355,0.025466,0.183837,0.847774,0.030455,0.056365

In [5]:
dataset.describe()

,isbn13,published_year,average_rating,num_pages,ratings_count,anger,disgust,fear,joy,sadness,surprise,neutral
count,5.230000e+03,5228.000000,5198.000000,5198.000000,5.198000e+03,5230.000000,5230.000000,5230.000000,5230.000000,5230.000000,5230.000000,5230.000000
mean,9.780668e+12,1999.841431,3.922205,348.417468,2.112707e+04,0.165170,0.201070,0.309483,0.281273,0.760640,0.223825,0.174097
std,6.022625e+08,9.076272,0.324957,229.903414,1.446344e+05,0.219034,0.213302,0.342726,0.318262,0.204569,0.248025,0.189087
min,9.780002e+12,1876.000000,0.000000,0.000000,0.000000e+00,0.000606,0.000821,0.000442,0.000550,0.000981,0.001251,0.000779
25%,9.780313e+12,1998.000000,3.750000,213.000000,1.830000e+02,0.064134,0.104007,0.051363,0.040564,0.549477,0.111690,0.078765
50%,9.780521e+12,2002.000000,3.940000,312.000000,1.124500e+03,0.064134,0.104007,0.094994,0.088914,0.838376,0.111690,0.078765
75%,9.780807e+12,2005.000000,4.120000,416.000000,6.570500e+03,0.139447,0.188806,0.587759,0.501138,0.936846,0.180352,0.198753
max,9.789028e+12,2019.000000,5.000000,3342.000000,5.629932e+06,0.989582,0.989417,0.995326,0.992068,0.974344,0.989361,0.983455

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5230 entries, 0 to 5229
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   isbn13              5230 non-null   int64
 1   isbn10              5230 non-null   object
 2   title               5230 non-null   object
 3   authors             5198 non-null   object
 4   categories          5198 non-null   object
 5   thumbnail           5061 non-null   object
 6   description         5230 non-null   object
 7   published_year      5228 non-null   float64
 8   average_rating      5198 non-null   float64
 9   num_pages           5198 non-null   float64
 10  ratings_count       5198 non-null   float64
 11  title_and_subtitle  5230 non-null   object
 12  tagged_description  5230 non-null   object
 13  simple_categories   5230 non-null   object
 14  anger               5230 non-null   float64
 15  disgust             5230 non-null   float64
 16  fear                5230 non-null   float64
 17  joy                 5230 non-null   float64
 18  sadness             5230 non-null   float64
 19  surprise            5230 non-null   float64
 20  neutral             5230 non-null   float64
dtypes: float64(11), int64(1), object(9)
memory usage: 858.2+ KB

In [9]:
dataset.drop(["isbn13","isbn10","title_and_subtitle","tagged_description", "anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"], axis=1, inplace=True)

In [10]:
dataset.sample()

,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,simple_categories
3676,Wizard's First Rule,Terry Goodkind,Fiction,http://books.google.com/books/content?id=fdpKP...,The masterpiece that started The New York Time...,2003.0,4.14,836.0,197049.0,Fiction

In [13]:
dataset.drop(["average_rating","ratings_count","categories"], axis=1, inplace=True)

In [14]:
dataset

,title,authors,thumbnail,description,published_year,num_pages,simple_categories
0,Gilead,Marilynne Robinson,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,247.0,Fiction
1,Spider's Web,Charles Osborne;Agatha Christie,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,241.0,Fiction
2,Rage of angels,Sidney Sheldon,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,512.0,Fiction
3,The Four Loves,Clive Staples Lewis,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,170.0,Nonfiction
4,The Problem of Pain,Clive Staples Lewis,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,176.0,Nonfiction
...,...,...,...,...,...,...,...
5225,Mistaken Identity,Nayantara Sahgal,http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,324.0,Fiction
5226,Journey to the East,Hermann Hesse,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,175.0,Nonfiction
5227,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,198.0,Fiction
5228,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,531.0,Nonfiction
5229,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,210.0,Nonfiction

In [16]:
dataset.to_csv("book.csv", index=False)